### PR TITLE
Install for all users

### PR DESCRIPTION
**Pull request by teknowledgist**
Makes this a machine install instead of a user install.

### CODE REVIEW

**Comment by majkinetor** [comment]
Thanks for the PR.  Will be online for the next release.

**Comment by Mailaender** [comment]
See https://chocolatey.org/faq#what-distinction-does-chocolatey-make-between-an-installable-and-a-portable-application for an alternative to hard-coding this setting.

**Comment by majkinetor** [comment]
@Mailaender, I am not sure what are you talking about, unless you talk about -iinstall-arguments which is the reason I removed this.

**Comment by Mailaender** [comment]
I mean you could solve it like https://chocolatey.org/packages/nsis with https://chocolatey.org/packages/nsis.portable and https://chocolatey.org/packages/nsis.install

**Comment by majkinetor** [comment]
No, that wont solve anything. 

First, there is no portable app by developer (in github releases). That means I would have to create a portable pandoc myself, then package it.

Second, this portable version would be then installed in $Env:chocolateyInstall\bin folder and that is the only difference. You can do that right now if you want by providing install argument. I could add the argument to the package for the location, but honestly, why bother ? Program Files is better location for all users anyway.

**Comment by teknowledgist** [comment]
I have to confess... I submitted the PR on the theory that it would work (as it is supposed to for .MSI installs) and because it Chocolatey packages are supposed to be machine installs, but I never tested it.  

I too see that it is not working.  There must be a problem with the .MSI, so I have posted a notice on the Pandoc forum.  Maybe the next version will have a working option to (silently) install for all users, as can be done in the GUI install.  It would be better if the next release set the property MSIINSTALLPERUSER="" instead of =1 as it is currently.  Then the SilentArgs could include ALLUSERS=2, to install for all users, but someone could always use -ia ALLUSERS="" (officially, ALLUSERS=0 is not an option) to install per user.

I have also not tested what happens if (with a working .MSI) there are multiple "ALLUSERS=x" statements.  I.E.  `msiexec /quiet /i pandoc.msi ALLUSERS=1 ALLUSERS=0`  If that works, then adding ALLUSERS=1 to the SilentArgs would be fine as the SilentArgs come before the --InstallArguments.

**Comment by majkinetor** [comment]
> I too see that it is not working

The strange thing is that it seems that it worked for @Mailaender because he got the message 'pandoc installed to 'C:\Program Files (x86)\Pandoc'.

**Comment by majkinetor** [comment]
Seems that folder can be set like this:

```
 msiexec /i "C:\Users\Korisnik\AppData\Local\Temp\chocolatey\pandoc\1.17.1\pandoc-1.17.1-1-windows.msi"  /Q APPLICATIONFOLDER='c:\pandoc'
```

**Comment by teknowledgist** [comment]
Setting the destination to c:\Program Files wouldn't be the same thing as a 
machine install.  For one thing, Pandoc would show up in the Programs and 
Features control panel only for the user who did the install.

**Comment by majkinetor** [comment]
Indeed. However, it would work for all users if machine path is changed. But that is all theoretical - nobody will ever want to use pandoc in such way.

This really seems like a pandoc installer issue.

**Pull request merged**
